language: r
sudo: true
cache: packages
branches:
    only:
        - master
        - stable
        - develop
r:
    - oldrel
    - release
    - devel
os:
    - linux
r_check_args: --as-cran --run-donttest --run-dontrun
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
