language: r
sudo: true
cache: packages
branches:
    only:
        - master
        - stable
        - develop
r:
    - oldrel
    - release
    - devel
os:
    - linux
    - osx
before_install:
    - sudo tlmgr install index
