language: r
sudo: true
cache: packages
branches:
    only:
        - master
        - stable
        - develop
r:
    - oldrel
    - release
    - devel
os:
    - linux
    - osx
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install texlive-latex-extra 
